export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const LOAD_HOME_PAGE_ARTICLES = 'LOAD_HOME_PAGE_ARTICLES';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';

export const FORGOT_PASSWORD_USER = 'FORGOT_PASSWORD_USER';
export const RECOVERY_PASSWORD_USER = 'RECOVERY_PASSWORD_USER';