export const DELETE_LOCATION = 'DELETE_LOCATION';
export const GET_LOCATION_COORDS = 'GET_LOCATION_COORDS';

export const START = '_START';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const ADD_LOCATION = 'ADD_LOCATION';

export const LOAD_HOME_PAGE_ARTICLES = 'LOAD_HOME_PAGE_ARTICLES';

export const SIGN_UP_FORM = 'SIGN_UP_FORM';
export const SIGN_IN_FORM = 'SIGN_IN_FORM';

export const LOAD_CUSTOMER_INFORMATION = 'LOAD_CUSTOMER_INFORMATION';
